name: Docker Build (PR)
on:
  pull_request:
    branches:
      - main
jobs:
  build-day5-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker image for Day 5
        run: docker build -t week3-day5-web:ci ./Week-3/Day-5/web